name: Chapter3
run-name: Run by @${{ github.actor }}
on: push
env: 
  FORMAT_FUNC: ${{format('{0}, {1}.', 'Hi', 'world')}}
  VARS_JSON: ${{toJSON(vars)}}
jobs: 
  generate-func:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - uses: actions/checkout@v4
      - run: printenv | grep '_FUNC'
      - run: echo VARS "${VARS_JSON} HASH ${HASH}"
        env: 
          HASH:  ${{hashFiles('.github/workflows/*.yml')}}
      # share vars
      - run: export TMP="hoge"
      - run: echo "${TMP}"
      - name: share vars
        id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - run: echo "${{toJSON(steps.*.ouputs)}}"
      - run: echo "${RESULT}"
        env: 
          RESULT: ${{steps.source.outputs.result}}
      # # conditional branch
      # - name: intentionally fail
      #   run : exit 1
      # - run: echo "failuer without conditional"
      # - run: echo "failuer with conditional"
      #   if: ${{failure()}}
      