name: manual
on: 
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: what's up
                required: true
                description: a cheerful word
            choice:
                type: choice
                options:
                    - info
                    - warn
                    - error
                required: false
env: 
    BRANCH: feature-gh-actions
    SEED: ${{vars.SEED}} # Variablesからの参照
    PASSWORD: ${{secrets.TMP_SECRETS}}
jobs:
    manual-run:
        runs-on: ubuntu-latest
        steps:
            - run: printenv
            - run: echo "${{inputs.greeting}}"
            - run: ls
            - run: pwd
            - run: 'echo actor: "${{github.actor}}", tmp_path: "${{runner.temp}}"'
            - run: echo "${BRANCH}"
            - run: echo "${GITHUB_PATH}"
            - run: echo "${GITHUB_ACTION}"
            - uses: actions/checkout@v6
              with: 
                ref: ${{ env.BRANCH }}
            - run: ls
            - run: pwd
            # Varibles
            - run: echo "${SEED}"
            # Secrets
            - run: echo "${PASSWORD} ${PASSWORD:0:1} ${PASSWORD#?}"

