name: manual
on:
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: what's up
                required: true
                description: a cheerful word
            choice:
                type: choice
                options:
                    - info
                    - warn
                    - error
                required: false
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{inputs.greeting}}"
            - run: ls
            - run: pwd
            - run: echo "contexts`:` {{github.actor}}"